export const el = {
  viewport: document.getElementById('viewport'),
  nodesLayer: document.getElementById('nodesLayer'),
  edgesSvg: document.getElementById('edges'),
  minimapSvg: document.getElementById('minimap'),
  runBtn: document.getElementById('runBtn'),
  status: document.getElementById('status'),
  query: document.getElementById('query'),
  finalContent: document.getElementById('finalContent'),
  finalDrawer: document.getElementById('finalDrawer'),
  liveStream: document.getElementById('liveStream'),
  liveEvents: document.getElementById('liveEvents'),
  liveTitle: document.getElementById('liveTitle'),
  liveSubtitle: document.getElementById('liveSubtitle'),
  collapseLiveBtn: document.getElementById('collapseLive'),
  hideLiveBtn: document.getElementById('hideLive'),
  showLiveBtn: document.getElementById('liveToggle'),
  nodePanel: document.getElementById('nodePanel'),
  nodePanelTitle: document.getElementById('nodePanelTitle'),
  nodeContent: document.getElementById('nodeContent'),
  closeNode: document.getElementById('closeNode'),
  hudFit: document.getElementById('hudFit'),
  hudZoomIn: document.getElementById('hudZoomIn'),
  hudZoomOut: document.getElementById('hudZoomOut'),
  palette: document.getElementById('palette'),
  paletteSearch: document.getElementById('paletteSearch'),
  paletteList: document.getElementById('paletteList'),
};
